### ISSUE TITLE
Support for Stream Deck XL

### ISSUE THREAD

**Issue by wischi-chr** [OpenMacroBoard/StreamDeckSharp#12]
2019-05-28 - _Ordered a Stream Deck XL_
2019-06-17 - _Stream Deck XL_ arrived (start development)
2019-06-19 - _Release v0.3.2_

**Finished (v0.3.2)**
- [x] SetKeyBitmap
- [x] KeyStateChanged event

**Finished (v0.3.4)**
- [x] GetFirmwareVersion
- [x] GetSerialNumber
- [x] ShowLogo
- [x] SetBrightness

**In progress**
- [ ] ConnectionStateChanged _(unknown/untested)_

**Comment by noodles4694** [comment]
Hi there, just wondered how you were getting on with this. I tried to do it myself in the code but hit a few snags with Report offsets. Would be great to get it soon - everyone is asking me to add support (and I can't wait to play with the 32 button version myself :))

**Comment by wischi-chr** [comment]
I'm already working on it. My best guess would be saturday maybe earlier.

**Comment by noodles4694** [comment]
We make a product called Hippotizer, you can see it in use here: https://www.youtube.com/watch?v=WRrk7gqizg8
Since we added Streamdeck support it has become one of the preffered control methods for our users, they love it - so thank you !

**Comment by noodles4694** [comment]
![JamiroquiTour](https://user-images.githubusercontent.com/51993166/59759434-f890f300-9287-11e9-9448-825d68829afb.jpg)
Here is a picture showing the streamdecks running Video control on the Jamiroquai tour 2 weeks ago

**Comment by wischi-chr** [comment]
Wow that looks amazing.

**Comment by wischi-chr** [comment]
@noodles4694 I just released StreamDeckSharp v0.3.2 (with StreamDeckXL support) a few minutes ago
https://www.nuget.org/packages/streamdecksharp/0.3.2

I've already tested it (and everything worked fine), but pls let me know if it works for you.

**Comment by noodles4694** [comment]
You are a Star ! Thank you, will get on the case today !

**Comment by noodles4694** [comment]
I updated the product today, all standard features are working however SetBrightness does not seem to work, and it also looks like show logo also does not work (not 100% on that last one, i am investigating further)

**Comment by wischi-chr** [comment]
I'm already working on that and updated the issue description to reflect the current state of development.

**Comment by wischi-chr** [comment]
@noodles4694 @BarRaider Just released v0.3.4 of StreamDeckSharp with full StreamDeckXL support. Let me know if something is missing.
