### ISSUE TITLE
It doesn't support for .net framework 3.5

### ISSUE THREAD

**Issue by rawat94** [OpenMacroBoard/StreamDeckSharp#14]
It doesn't support for .net framework 3.5

**Comment by Vittel** [comment]
What's the reason to use such an outdated framework?

**Comment by Vittel** [comment]
I don't see an obvious reason why it wouldn't work with 3.5. have you tried compiling both projects with 3.5?

**Comment by wischi-chr** [comment]
It does not support 3.5 and I'm not going to maintain that (I even thought about dropping .net 4 support) - but in theory you should be able to port it to 3.5
