### ISSUE TITLE
Not working with Unity Api compatibility level= .net 4.x

### ISSUE THREAD

**Issue by rawat94** [OpenMacroBoard/StreamDeckSharp#15]
Hi,
I am trying to add the dll in unity api version=4.x but It is throwing error 
Error:- The dll is not allowed to be included

**Comment by wischi-chr** [comment]
I'm not a unity expert, but my guess is that unity just uses C# for scripting and complaints about the HidSharp library because it invokes (for obvious reasons) WinAPI stuff, but that's just a guess.

**Comment by rawat94** [comment]
Hi,
Thanks for the link.
But can i get this project dll build on .net standard 2.0

**Comment by wischi-chr** [comment]
There is no nuget package for .netstandard yet but take a look at the most recent commits.

**Comment by rawat94** [comment]
![image](https://user-images.githubusercontent.com/38307422/60415348-86f66480-9bf8-11e9-82f7-031bb9f93ba2.png)

**Comment by rawat94** [comment]
![image](https://user-images.githubusercontent.com/38307422/60426666-c0d46480-9c12-11e9-8726-1355570fc5b6.png)

**Comment by rawat94** [comment]
can we replace presentation framework to another dll which will support in Unit ??
Any suggestion
 
-- TIA

**Comment by wischi-chr** [comment]
> There is no nuget package for .netstandard yet but take a look at the most recent commits.

There will be a .netstandard version in a few weeks but if you want to experiment with it sooner you can clone the repo instead of using the nuget packages and check out the most recent commits

**Comment by rawat94** [comment]
How to read stream key information.
Example I have defined key as System: Text type and added string content defined as value. I'm interested to read the value through program. I'm able to debug StreamdeckSharp.dll. I was reading StreamDeckHardwareInfo class file but the class has no information related key content.

Please let us know how to read this value.
