### ISSUE TITLE
nuget version 0.3.5 dependent on non-existing version of OpenMacroBoard.sdk

### ISSUE THREAD

**Issue by BarRaider** [OpenMacroBoard/StreamDeckSharp#20]
When trying to install latest release of StreamDeckSharp (v0.3.5 from nuget) there is an error message:

Unable to find a version of 'OpenMacroBoard.SDK' that is compatible with 'StreamDeckSharp 0.3.5 constraint: OpenMacroBoard.SDK (>= 0.4.0 && < 1.0.0)'.				

It seems OpenMacroBoard.SDK was not updated in nuget to the newer version and as such, cannot install StreamDeckSharp through nuget

**Comment by BarRaider** [comment]
Is there an upcoming fix for this?

**Comment by wischi-chr** [comment]
Hi, thanks for reporting that.
Sadly I'm a bit short on time at the moment; I plan on fixing it next week.

**Comment by wischi-chr** [comment]
I checked it a few minutes ago and last time I update the package I even built it but forgot to upload it to nuget. Should be fixed now. Pls let me know if it works.
