### ISSUE TITLE
Feature request: Button down creates smaller image

### ISSUE THREAD

**Issue by TripleNico** [OpenMacroBoard/StreamDeckSharp#31]
First of all, my compliments about your library. It is really easy to use and well documented, keep up the good work!

If you have some time left it would be great is you can add a Property that enables "Make image smaller on button down". What do i mean? Well lets say the image is 100,100 when i push the button i would like to see that the image would be downsized to let's say 80,80 and when i release the button it returns to it's original size 100,100

This way the push action of a button is more like a software button. I noticed this behaviour if you use the stock StreamDeck software.

**Comment by wischi-chr** [comment]
That would probably be a feature for OpenMacroBoard and not the StreamDeckSharp provider. The `StreamDeckSharp` provider is intended to be a pretty slim.
