### ISSUE TITLE
Change title and icon

### ISSUE THREAD

**Issue by supermac** [OpenMacroBoard/StreamDeckSharp#37]
Hi everyone!

Is it possible to change the title of a button? and its icon?

Thanks.

**Comment by wischi-chr** [comment]
Hi.

Yes sure. You can load any icon you want, for example like so: `var bitmap = KeyBitmap.Create.FromFile("icon.png")` and send it to any key `deck.SetKeyBitmap(keyId, bitmap)`.

**Comment by supermac** [comment]
Thanks for the reply.

I know this option, but when I use it, the title of the button disappears and you only see this bitmap.

What I ask is if you can change only the icon of the button (on background), without losing the title.

And on the other hand if it is possible to change the title??

**Comment by wischi-chr** [comment]
Could you post the code that you are using now?

**Comment by wischi-chr** [comment]
I'm closing this ticket because of inactivity. Let me know if you need more help.
