### ISSUE TITLE
StreamDeck XL Button Rows 1-3 not trigger KeyStateChanged

### ISSUE THREAD

**Issue by patrick-dmxc** [OpenMacroBoard/StreamDeckSharp#38]
Hi, i found some strange behavior.
In this smal Test-Program, the StreamDeck XL not tigger the KeyStateChanged event on the Rows 1,2, and 3, only the 4th row triggers the event.
[StreamDeck.zip](https://github.com/OpenMacroBoard/StreamDeckSharp/files/7444950/StreamDeck.zip)

**Comment by wischi-chr** [comment]
Hi @patrick-dmxc 

I've tested it on my stream deck xl and all buttons trigger the state change as expected. Do you still have this issue?
Could you please try to connect with the uncached StreamDeckClient like so and test if this fixes the issue.

```csharp
var streamDeckReference = StreamDeck.EnumerateDevices(Hardware.StreamDeckXL).First();
streamDeckReference.UseWriteCache = false;

using (var board = streamDeckReference.Open())
{
    // do stuff with the board, register eventhandler etx.
}
```

You should also try to connect the StreamDeckXL directly to your PC (without a hub). I experienced issues and glitches with the Stream Deck XL in the past as well with my usb hub.

**Comment by patrick-dmxc** [comment]
Apparently it was due to a bridged firmware.
But can you please publish a new version for the two projects on NuGet
