### ISSUE TITLE
Could not load HidSharp...

### ISSUE THREAD

**Issue by dxh-sc** [OpenMacroBoard/StreamDeckSharp#43]
I have two project, one use the nuget package "StreamDeckSharp", another one use the nuget package "HidSharp".
If the following hidsharp overwrites the previous HidSharp.dll,  will see the error "could not load hidsharp...." for the StreamDeckSharp.

so i think there two hidsharp.dll have some conflicts.

so why not reference HidSharp nuget directly on this project(StreamDeckSharp)?

or i miss something?

I put down the source code, modify the reference, and then compile it,  it works and i didn't see any mistakes either.

**Comment by wischi-chr** [comment]
Currently hidsharp is included in this repo because I strongly named it (because StreamDeckSharp is also strongly named) and the hidsharp nuget package isn't.

This will probably be changed in the upcoming StreamDeckSharp release (because I'm probably dropping the strong name signature) and hidsharp will be referenced as a regular nuget package.

**Comment by dxh-sc** [comment]
> 



> Currently hidsharp is included in this repo because I strongly named it (because StreamDeckSharp is also strongly named) and the hidsharp nuget package isn't.
> 
> This will probably be changed in the upcoming StreamDeckSharp release (because I'm probably dropping the strong name signature) and hidsharp will be referenced as a regular nuget package.

**Comment by dxh-sc** [comment]
> 

thanks!!!

it is very nice to have it.

**Comment by wischi-chr** [comment]
@dxh-sc If you still have this issues you can try out the new [v4.0.0-preview](https://www.nuget.org/packages/StreamDeckSharp/4.0.0-preview) it no longer uses strongly named assemblies and thus doesn't depend on a bundled hidsharp anymore.
