### ISSUE TITLE
ClearKey only clears part of the key when different sized Stream Decks are connected

### ISSUE THREAD

**Issue by jskeet** [OpenMacroBoard/StreamDeckSharp#44]
I've got a Stream Deck and a Stream Deck XL. When both are used in the same application, calling `deckXL.ClearKeys()` only clears part of each Stream Deck XL key.

I believe this is because the XL keys are 96x96, whereas the Stream Deck keys are 72x72.

`StreamDeckJpgHardwareBase.cachedNullImage` is a static field, so it assumes the same null image can be used for all hardware - but its size depends on the instance that `GetNullImage` was first called on.

I suspect that just making `cachedNullImage` an instance field would be fine here - if I've read the code correctly, there are only normally 4 instances of `StreamDeckJpgHardwareBase` anyway, so it's not like it's hugely wasteful.

**Comment by wischi-chr** [comment]
The field is now an instance field in [v4.0.0-preview](https://www.nuget.org/packages/StreamDeckSharp/4.0.0-preview).

Pls let me know if this fixes your issue wich `ClearKey`
