### ISSUE TITLE
Exceptions when disposing of a deck in WPF

### ISSUE THREAD

**Issue by jskeet** [OpenMacroBoard/StreamDeckSharp#45]
Not sure if this is WPF-specific, but I wouldn't have thought so...

To reproduce:

- Create new WPF application (I'm using .NET 6)
- Add StreamDeckSharp dependency (3.2.0)
- Create a button in the main window, with a Click action of OpenAndDispose
- Add code as shown below:

```csharp
private void OpenAndDispose(object sender, RoutedEventArgs e)
{
    var devices = StreamDeck.EnumerateDevices().ToList();
    var device = devices[0];
    var deck = StreamDeck.OpenDevice(device.DevicePath);
    deck.Dispose();
}
```

- Run the code and click the button

Each time the button is clicked, there are three exceptions:

- At StreamDeckSharp.Internals.ConcurrentBufferedQueue\`2.Take() - System.InvalidOperationException: 'Adding is completed and buffer is empty.'
- At HidSharp.Platform.Windows.NativeMethods.OverlappedOperation(IntPtr ioHandle, IntPtr eventHandle, Int32 eventTimeout, IntPtr closeEventHandle, Boolean overlapResult, NativeOverlapped* overlapped, UInt32& bytesTransferred) - System.ObjectDisposedException: 'Closed.'
- At HidSharp.AsyncResult`1.EndOperation() - System.ObjectDisposedException: 'Closed.'

Is there a safe way of disposing of the deck objects?

**Comment by wischi-chr** [comment]
Currently all of those exceptions are handled and shouldn't really surface. Besides the fact that using exceptions for control flow is probably not a good design decision those exceptions shouldn't prevent anything from being disposed safely or am I missing something?

**Comment by jskeet** [comment]
Only that they're a bit worrying in terms of potentially being a sign of something else being wrong (and showing up in VS output, which makes me wonder whether they're not actually being handled).

**Comment by wischi-chr** [comment]
I just released a preview version [v4.0.0-preview](https://www.nuget.org/packages/StreamDeckSharp/4.0.0-preview). This is a breaking change, but it should be pretty straight forward to migrate. This version also fixes the "exceptions for control flow" situation in the device Dispose method.

Pls let me know if it works for you.

**Comment by jskeet** [comment]
Fabulous - thanks so much. I'll test all of these over the weekend.

**Comment by jskeet** [comment]
Yup, they all look good for me, thanks - see https://github.com/jskeet/DemoCode/commit/87c8c65d14dbc1710cffc4ba3febe228ff86475d for the migration, if anyone else needs to do the same thing.

**Comment by ocdtrekkie** [comment]
@jskeet That's a super useful link that @wischi-chr may wish to link to or reference elsewhere. I saw some comments about having to "migrate" to 4.0.0, but not a super clear example of how to do so.

**Comment by jskeet** [comment]
@ocdtrekkie: Glad it's useful! It's worth noting that this is a fairly simple project - there may well be other migration changes required that I haven't covered, but if it's a useful starting point, that's great :)

**Comment by wischi-chr** [comment]
@jskeet thank you for sharing the changes you had to make. @ocdtrekkie sadly I'm currently a bit short on time so there is no "good" migration guide at the moment. You could also take a look at the changes of the example projects [here](https://github.com/OpenMacroBoard/OpenMacroBoard.ExampleCollection/compare/1104c4f...3203bff).

I added both links (jons DemoCode project and the diff view of the ExampleCollection repository to the README.md of this repository).
