### ISSUE TITLE
FW 1.02.007 problem

### ISSUE THREAD

**Issue by Devnuel14** [OpenMacroBoard/StreamDeckSharp#46]
https://www.reddit.com/r/elgato/comments/t9u9u0/is_there_a_way_to_downgrade_the_firmware_of_the/?utm_medium=android_app&utm_source=share

Guys, how can I reset my firmware?

**Comment by Devnuel14** [comment]
> Hi @Devnuel14
> 
> This repository is for .NET developers and (as stated in the README.md) is not official and not from Elgato.
> Your best bet would probably to directly contact the [Elgato Support](https://help.elgato.com/).
> 
> I (and this library) can't really help you with firmware issues, but only if you have troubles using the StreamDeckSharp nuget package (which is intended to be used by programmers and not by end-users).
> 

I am a developer, how can I use this project on my streamdeck? Only I need to run this in visual studio with my streamdeck connected or how it works?

**Comment by wischi-chr** [comment]
Exactly. The simplest way to start would be to use one of the example projects.

The rainbow example would probably be a good start:
https://github.com/OpenMacroBoard/OpenMacroBoard.ExampleCollection/blob/master/src/OpenMacroBoard.Examples.Rainbow/Program.cs

Regarding your initial question: Keep in mind that streamdecksharp can't upgrade or downgrade the firmware, you need the official StreamDeck Software for that.

**Comment by Devnuel14** [comment]
Do you have any idea how to downgrade the firmware of my streamdeck? Using the software of stream deck does not help because there is no option to do that and also they wanted me to send my device to them to replace it (not possible because it will be expensive for me because I am in another country) :(

**Comment by wischi-chr** [comment]
No sadly I don't. I'm not even sure that the firmware is what's causing it. The displays on the keys are really just a single large display so it could also be a defect screen. Have you opened a support ticket with Elgato yet?

**Comment by Devnuel14** [comment]
I think it is a general problem with the firmware, if you check Twitter you can see there are other people with the same problem: https://twitter.com/strawbelliott/status/1475894755624034304

**Comment by Devnuel14** [comment]
Seems that the only way to solve it is to wait for the next firmware update... very very anoying

**Comment by asdf23** [comment]
please don't share reddit links. I was happy to take a look at this issue but when I click this 3rd party link I get some popup to install some app and cannot continue to see the content. Oh well ignored
