### ISSUE TITLE
StreamDeckXL Rev2

### ISSUE THREAD

**Issue by patrick-dmxc** [OpenMacroBoard/StreamDeckSharp#51]
Hi, the StreamDeck XL has received an new revision and withit an new Product-ID 0x008F

https://forum.dmxcontrol-projects.org/index.php?thread/16862-stream-deck-wird-nicht-erkannt-dmxc-3-2-3/&postID=140915#post140915

https://github.com/abcminiuser/python-elgato-streamdeck/pull/100/commits/3e497ff80083cfb106310ea3aa029dfdc10ff370

**Comment by flat-eric147** [comment]
Here's a patch that works for me.
[patch_StreamDeckXlRev2Support.zip](https://github.com/OpenMacroBoard/StreamDeckSharp/files/11233273/patch_StreamDeckXlRev2Support.zip)

**Comment by patrick-dmxc** [comment]
Why you post this?
i opened a pull-request with a fix for this, the Repo-Owner only has to accept it and thats it 😅

**Comment by flat-eric147** [comment]
How would I know?

**Comment by patrick-dmxc** [comment]
The Pull-Request is attached to the first post direct above your comment...

**Comment by wischi-chr** [comment]
The new version (v5.0.0 via nuget) supports the `Stream Deck XL Rev2`, let me know if it works for you.

**Comment by wischi-chr** [comment]
Feel free to reopen a new issue if it doesn't work as expected.
